version: '2'

services: 
    backend:
        build:
            context: .
        environment: 
            ConnectionStrings__Msaas: "Host=db;Database=msaas;Username=postgres;Password=${DB_PASSWORD}"
            JwtSettings__ExpiresIn: 604800
            JwtSettings__SigningKey: ${JWT_SIGNING_KEY}
        ports:
            - ${PORT}:80
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: msaas
        volumes:
            - data:/var/lib/postgresql/data

volumes:
    data:
